/**
 * 全片阶段表（id 0–14）
 * blocking: null | { type:'click' } | { type:'clicks', count:6 } | { type:'click-after', afterMs }
 * durationMs: 自动阶段时长；与 blocking 并存时先等 blocking 再计时（由 director 解释）
 */
(function (global) {
    'use strict';

    global.STAGES_CONFIG = [
        {
            id: 0,
            key: 'intro-snowflake',
            handledByMain: true,
            durationMs: null,
            blocking: { type: 'click' },
            subtitles: [],
            layers: { bgVideo: true, effect: null, houseModel: false, karmaBar: false, blockingUi: null },
            threeProfile: 'r128',
            collectInteraction: true,
            startMarketSession: true,
        },
        {
            id: 1,
            key: 'diamond-sutra',
            durationMs: null,
            blocking: null,
            subtitles: [],
            layers: { bgVideo: true, effect: null, houseModel: false, karmaBar: false },
            threeProfile: 'r128',
            collectInteraction: true,
        },
        {
            id: 2,
            key: 'repel-touch',
            durationMs: null,
            blocking: { type: 'click-after', afterMs: 4000, postClick: 'collapse-effect' },
            subtitles: [
                { text: 'The point of touch. Descending without awareness.', atMs: 0 },
                { text: 'Volition. Blind form-shaping.', atMs: 4000 },
            ],
            layers: { bgVideo: true, effect: 'repel-particles', houseModel: false, karmaBar: false },
            threeProfile: 'p5',
            collectInteraction: true,
        },
        {
            id: 3,
            key: 'house-expand',
            durationMs: 7000,
            blocking: null,
            subtitles: [{ text: 'The Other. Mirroring the illusory self.', atMs: 0, durationMs: 7000, fadeDelayMs: 0 }],
            layers: { bgVideo: true, effect: null, houseModel: 'expand', karmaBar: false },
            threeProfile: 'r128',
            collectInteraction: true,
        },
        {
            id: 4,
            key: 'house-particleize',
            durationMs: 9000,
            blocking: null,
            subtitles: [{ text: 'Apparition. Entangling into flesh and blood.', atMs: 0, durationMs: 9000, fadeDelayMs: 0 }],
            layers: { bgVideo: true, effect: null, houseModel: 'particleize', karmaBar: false },
            threeProfile: 'r128',
            collectInteraction: true,
        },
        {
            id: 5,
            key: 'capturing-six',
            durationMs: null,
            blocking: { type: 'six-nodes', count: 6 },
            subtitles: [{ text: 'Capturing a faint flicker. Pushing through the echoing rift.', atMs: 0 }],
            layers: { bgVideo: true, effect: null, houseModel: 'six-circles', karmaBar: false, blockingUi: null },
            threeProfile: 'r128',
            collectInteraction: true,
            playNotesOnClick: false,
        },
        {
            id: 6,
            key: 'house-chu',
            durationMs: 7500,
            blocking: null,
            subtitles: [{
                text: 'Touch. Awakening the dormant pulse. You feel not the barrier, but the collective tremor of cosmic dust.',
                atMs: 0,
                durationMs: 7500,
                fadeDelayMs: 0,
            }],
            layers: { bgVideo: true, effect: null, houseModel: 'chu', karmaBar: false },
            threeProfile: 'r128',
            collectInteraction: true,
        },
        {
            id: 7,
            key: 'house-shou',
            durationMs: 8000,
            blocking: null,
            subtitles: [{
                text: 'Vedana. Resonance. The current is received as pleasure.',
                atMs: 0,
                durationMs: 8000,
                fadeDelayMs: 0,
            }],
            layers: { bgVideo: true, effect: null, houseModel: 'shou', karmaBar: false },
            threeProfile: 'r128',
            collectInteraction: true,
        },
        {
            id: 8,
            key: 'house-ai',
            durationMs: 8000,
            blocking: null,
            subtitles: [{
                text: 'Craving. Dust gathers, and the house becomes a sphere of wanting.',
                atMs: 0,
                durationMs: 8000,
                fadeDelayMs: 0,
            }],
            layers: { bgVideo: true, effect: null, houseModel: 'ai', karmaBar: false },
            threeProfile: 'r128',
            collectInteraction: true,
        },
        {
            id: 9,
            key: 'house-qu',
            durationMs: 8000,
            blocking: null,
            subtitles: [{
                text: 'Clinging. The sphere is held, and wanting takes root.',
                atMs: 0,
                durationMs: 8000,
                fadeDelayMs: 0,
            }],
            layers: { bgVideo: true, effect: null, houseModel: 'qu', karmaBar: false },
            threeProfile: 'r128',
            collectInteraction: true,
        },
        {
            id: 10,
            key: 'karma-collapse',
            durationMs: null,
            blocking: null,
            karmaDurationMs: 7000,
            karmaLabel: 'Karma calculation in progress...',
            subtitles: [],
            layers: { bgVideo: true, effect: null, houseModel: 'qu', karmaBar: true },
            threeProfile: 'r128',
            collectInteraction: true,
            finalizeKarma: true,
        },
        {
            id: 11,
            key: 'six-paths-reveal',
            durationMs: 20000,
            blocking: null,
            subtitles: 'six-paths-fixed',
            layers: { bgVideo: false, effect: 'assigned-path', houseModel: false, karmaBar: false },
            threeProfile: 'dynamic',
            collectInteraction: false,
        },
        {
            id: 12,
            key: 'woven-ring',
            durationMs: 6000,
            blocking: null,
            subtitles: [{ text: 'Woven as an algorithmic birthmark, cast as the first computed shadow.', atMs: 0 }],
            layers: { bgVideo: true, effect: null, houseModel: 'ring-flow', karmaBar: false },
            threeProfile: 'r128',
            collectInteraction: false,
        },
        {
            id: 13,
            key: 'uninstall-fade',
            durationMs: 10000,
            blocking: null,
            subtitles: [{ text: 'Uninstall every illusion here, relinquish all to the echo-less void.', atMs: 0 }],
            layers: { bgVideo: true, effect: null, houseModel: 'fade', karmaBar: false },
            threeProfile: 'r128',
            collectInteraction: false,
        },
        {
            id: 14,
            key: 'final-quote',
            durationMs: null,
            blocking: null,
            subtitles: [{
                text: 'No one stands alone; we are the particles of dust, sampled and shared in the air we breathe.',
                atMs: 0,
            }],
            layers: { bgVideo: true, effect: null, houseModel: false, karmaBar: false },
            threeProfile: 'r128',
            collectInteraction: false,
        },
    ];
})(typeof window !== 'undefined' ? window : this);
